#######################################
#          Night status               #
#######################################
- alias: enable night
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination
    below: 300
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.trigger_night

- alias: disable night
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination
    above: 500
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.trigger_night

#######################################
#          Gateway light on mvt       #
#######################################
- alias: Turn on Gateway Light when there is movement
  trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor
      to: 'on'
  condition:
        condition: state
        entity_id: input_boolean.trigger_night
        state: 'on'
  action:
      service: homeassistant.turn_on
      entity_id: light.gateway_light
      data:
        brightness: 255
        rgb_color: [255,255,255]

- alias: Turn off Gateway light 1 minute after last movement
  trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0
  action:
      service: homeassistant.turn_off
      entity_id: light.gateway_light