homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_val
  longitude: !secret longitude_val
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_val
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Tokyo
  # Include Packages
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
weather:
  - platform: openweathermap
    api_key: !secret key_owm
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - clouds
      - rain
      - snow

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Device Tracking
# MQTT (Local Broker)
mqtt:
#  broker: !secret local_mqtt_broker
#  port: !secret local_mqtt_port
#  username: !secret local_mqtt_username
#  password: !secret local_mqtt_password

#   Owntracks
device_tracker:
## MQTT / Zanzito based device tracking
#  - platform: mqtt_json
#    devices:
#      USER1_phone: zanzito/trent/location
# NMAP Based Device Tracking
  - platform: nmap_tracker
    hosts: !secret hosts_device_tracker
    exclude:
     - !secret exclude_device_tracker
  - platform: bluetooth_tracker
  - platform: owntracks

xiaomi_aqara:
  discovery_retry: 5
  gateways:
      - host: !secret host_ac_xiaomi_aqara
        mac: !secret mac_ac_xiaomi_aqara
        key: !secret key_ac_xiaomi_aqara
      - host: !secret host_xiaomi_aqara
        mac: !secret mac_xiaomi_aqara
        key: !secret key_xiaomi_aqara
light:
  - platform: yeelight
    devices:
      !secret host_bedside_lamp:
        name: Bedside Lamp
        transition: 1000
        use_music_mode: True # default to False
        save_on_change: True # default to True

media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: true
    use_custom_entity_ids: true
    use_episode_art: true

#######################################
#          Includes                   #
#######################################

group: !include groups.yaml
automation: !include_dir_merge_list includes/automation
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml