###############################################################################
#   @author         :   Trent Stanton
#   @date           :   24/02/2018
#   @package        :   Weather
#   @description    :   Weather information for Home Assistant interface
#   @url            :
###############################################################################
group:
  weather:
    name: Weather
    control: hidden
    entities:
      - sun.sun
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_daily_low_temperature
      - sensor.weather_daily_high_temperature
      - sensor.weather_precip_intensity
      - sensor.weather_humidity
#      - weather.melbourne_forecast

sensor:

# Dark Sky Weather
  - platform: darksky
    api_key: !secret key_darksky
    update_interval: '00:05:00'
    name: Weather
    monitored_conditions:
      - summary
#      - icon
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - precip_type
      - precip_intensity
#      - precip_probability
      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
      - humidity
#      - pressure
      - visibility
#      - ozone
#      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max

#weather:
#  - platform: yweather
#    name: Melbourne Forecast